### ISSUE TITLE
Lag and possible drops caused by WiFi Scans

### ISSUE THREAD

**Issue by ahasbini** [tomaspinho/rtl8821ce#143] opened 2020-05-26 17:23 UTC
Hi,

I've been facing a problem with the rtl8821ce driver and I experienced it in this repository and the one provided by Ubuntu in "Additional Drivers" app.

I've performed some debugging with this repository by enabling the debug flag in `Makefile` and running a ping command to my local network gateway IP (192.168.1.1). It appears to me that whenever a WiFi scan is performed while connected (or associated) with a WiFi or SSID, a lag is induced. I tried to reproduce this by triggering the WiFi scan manually (I triggered it by just opening the WiFi settings in Ubuntu, it automatically does the scan when the menu item gets focused), and was able to observe the same behavior.

```shell
ahasbini@ahasbini-ubuntu:/$ uname -a 
Linux ahasbini-ubuntu 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
ahasbini@ahasbini-ubuntu:/$ dkms status 
nvidia, 440.64, 5.4.0-29-generic, x86_64: installed
nvidia, 440.64, 5.4.0-31-generic, x86_64: installed
rtl8821ce, v5.5.2_34066.20200325, 5.4.0-31-generic, x86_64: installed
virtualbox, 6.1.6, 5.4.0-29-generic, x86_64: installed
virtualbox, 6.1.6, 5.4.0-31-generic, x86_64: installed
ahasbini@ahasbini-ubuntu:/$ lsmod | grep 8821
8821ce               2207744  0
cfg80211              704512  1 8821ce
```

`dmesg` output:
```
[17523.278950] RTW: cfg80211_rtw_scan(wlp3s0)
[17523.279151] RTW: [HW_VAR_CHECK_TXBUF] Empty in 0 ms
[17523.279169] RTW: wlp3s0 sleep m0=0x00000003, ori reg_0x4d4=0x00000000
[17524.036117] RTW: ERROR [RFK-CHK] RF-K not allowed due to ifaces under site-survey
[17525.620204] RTW: scan_abort_hdl idx:37
[17525.620604] RTW: wlp3s0 wakeup m0=0x00000003, ori reg_0x4d4=0x00000003
[17525.626278] RTW: survey done event(14) band:0 for wlp3s0
[17525.626407] RTW: rtw_indicate_scan_done(wlp3s0)
```

`ping` output (notice the high time value for sequences 1639 --> 1642):
```
64 bytes from 192.168.1.1: icmp_seq=1635 ttl=64 time=10.8 ms
64 bytes from 192.168.1.1: icmp_seq=1636 ttl=64 time=5.31 ms
64 bytes from 192.168.1.1: icmp_seq=1637 ttl=64 time=19.8 ms
64 bytes from 192.168.1.1: icmp_seq=1638 ttl=64 time=2.59 ms
64 bytes from 192.168.1.1: icmp_seq=1639 ttl=64 time=3579 ms
64 bytes from 192.168.1.1: icmp_seq=1640 ttl=64 time=2554 ms
64 bytes from 192.168.1.1: icmp_seq=1641 ttl=64 time=1532 ms
64 bytes from 192.168.1.1: icmp_seq=1642 ttl=64 time=509 ms
64 bytes from 192.168.1.1: icmp_seq=1643 ttl=64 time=2.35 ms
64 bytes from 192.168.1.1: icmp_seq=1644 ttl=64 time=2.41 ms
64 bytes from 192.168.1.1: icmp_seq=1645 ttl=64 time=2.30 ms
64 bytes from 192.168.1.1: icmp_seq=1646 ttl=64 time=6.26 ms
64 bytes from 192.168.1.1: icmp_seq=1647 ttl=64 time=2.34 ms
```

I thought of disabling the periodic background scans by fixating the BSSID as mentioned [here](https://blogs.gnome.org/dcbw/2016/05/16/networkmanager-and-wifi-scans/) but that doesn't seem to have an effect. I could also disable `NetworkManager` service and then do things manually in shell using `wpa_supplicant` and related but I honestly prefer having the GUI control provided so I'd be happy to help in debugging and fixing this if someone would point me to some directions. Thanks!

**Comment by javis86** [comment] 2020-08-10 16:56
Facing same problem. Ubuntu 20.04. Firing "iwlist wlo1 scan" manually i could reproduce it.

**Comment by anibalardid** [comment] 2020-10-19 19:23
Hi !  @ahasbini ,
I have the same problem :( 
could you resolve it ?

**Comment by ahasbini** [comment] 2020-10-20 02:42
@anibalardid honestly I didn't and ended up switching to another laptop after some time, giving away the laptop with rtl8821ce to someone else with Windows 10 on it.

**Comment by anibalardid** [comment] 2020-10-20 02:59
thanks ! 
today I fixed installing latest code on github repo of this repo.
It works ! I havent drops anymore.
But the connection to my router is so weird. because I have more than router, and sometimes connected to the most far ... so the connection has low level.

**Closed** 2020-10-20 07:37 UTC

**Comment by macieksk** [comment] 2021-04-04 20:22
Hi, 
Thanks for pointing this out. I had a similar problem with `rtl8812au` https://github.com/aircrack-ng/rtl8812au
I was able to solve this by changing `scan_ch_ms` to 0:

```bash
$ sudo bash -c 'echo 4 > /proc/net/rtl88XXau/log_level'   
## optional ^ for debug output in dmesg, 
## this requires compiling the driver with  CONFIG_RTW_DEBUG = y set in Makefile

$ cat /proc/net/rtl88XXau/wlxd03745eb2898/scan_param
scan_ch_ms rx_ampdu_accept rx_ampdu_size backop_ms scan_cnt_max
100        255             255           400       3           

$ sudo bash -c 'echo 0 255 255 400 3 > /proc/net/rtl88XXau/wlxd03745eb2898/scan_param'

$ cat /proc/net/rtl88XXau/wlxd03745eb2898/scan_param
scan_ch_ms rx_ampdu_accept rx_ampdu_size backop_ms scan_cnt_max
0          255             255           400       3   
```

Apparently `scan_ch_ms` cannot be set using a module option (which are listed below). Is there any other way to fix it?
```bash
if2name --> wlan%d
ifname --> wlan%d
rtw_adaptivity_en --> 0
rtw_adaptivity_mode --> 0
rtw_adaptivity_th_edcca_hl_diff --> 0
rtw_adaptivity_th_l2h_ini --> 0
rtw_ampdu_enable --> 1
rtw_amplifier_type_2g --> 0
rtw_amplifier_type_5g --> 0
rtw_antdiv_cfg --> 2
rtw_antdiv_type --> 0
rtw_beamform_cap --> 10
rtw_busy_thresh --> 40
rtw_bw_mode --> 33
rtw_channel --> 1
rtw_channel_plan --> 255
rtw_check_hw_status --> 0
rtw_chip_version --> 0
rtw_ch_switch_offload --> 0
```
