### ISSUE TITLE
Ubuntu 18.10 Kernel 4.18.0-10 Driver not working properly

### ISSUE THREAD

**Issue by plane000** [tomaspinho/rtl8821ce#14] opened 2018-11-24 22:38 UTC
Driver works as specified, cannot connect to wifi networks.

DMESG shows a number of errors, naimly: more of the logs are on: https://pastebin.com/Fiayc8rP

    [19434.972318] RTW: wlp5s0- hw port(0) mac_addr =60:14:b3:b1:b1:47
    [19434.972805] RTW: nolinked power save leave
    [19434.972865] RTW: WARN Unhandled ISR = 20000000, 0, 0
    [19437.273507] RTW: nolinked power save enter
    [19497.483423] swiotlb_tbl_map_single: 27 callbacks suppressed
    [19497.483430] rtl8821ce 0000:05:00.0: swiotlb buffer is full (sz: 5120 bytes)
    [19497.483436] rtl8821ce 0000:05:00.0: DMA: Out of SW-IOMMU space for 5120 bytes
    [19497.500314] RTW: ERROR [HALMAC]Polling Bcn_Valid_Fail error!!
    [19497.500320] RTW: ERROR [HALMAC]PLATFORM_SEND_RSVD_PAGE 0 error!!
    [19497.500322] RTW: ERROR [HALMAC]halmac_send_fwpkt_88xx fail!!
    [19497.500338] RTW: nolinked power save leave

I have recompiled, reinstalled the dependencies and everything i could think of. It looks like a bug, im not sure though, am i doing something wrong?

Networks are discoverable and i can see them and attempt to connect to them, however i can't connect.

**Comment by plane000** [comment] 2018-11-24 23:01
the error including

    [25461.418512] rtl8821ce 0000:05:00.0: swiotlb buffer is full (sz: 5120 bytes)
    [25461.418520] rtl8821ce 0000:05:00.0: DMA: Out of SW-IOMMU space for 5120 bytes
    [25461.418914] rtl8821ce 0000:05:00.0: swiotlb buffer is full (sz: 5120 bytes)
    [25461.418919] rtl8821ce 0000:05:00.0: DMA: Out of SW-IOMMU space for 5120 bytes
    [25461.435528] RTW: ERROR [HALMAC]Polling Bcn_Valid_Fail error!!
    [25461.435539] RTW: ERROR [HALMAC]PLATFORM_SEND_RSVD_PAGE 0 error!!
    [25461.435541] RTW: ERROR [HALMAC]halmac_send_fwpkt_88xx fail!!
    [25461.435560] RTW: nolinked power save leave

is produced when connecting to a network

**Comment by tomaspinho** [comment] 2018-11-25 16:51
Can you post more information regarding your hardware?
Laptop model/maker, a listing of `lspci -k` and `lsusb -v`?
Looks like a power management issue, because the card seems to be turning off and on again, have you looked at the PCIe Power Management section in the readme?

**Comment by tomaspinho** [comment] 2018-11-26 10:50
@plane000 I'm using the exact same laptop with Ubuntu 18.10 with kernel `4.18.0-11-generic`, without any issues.

Do you happen to have `laptop-mode-tools` installed? Are you running `powertop`?

**Comment by plane000** [comment] 2018-11-26 11:22
It's a long story haha, I switched back to windows 10 because I need WiFi for school, so I have Ubuntu and windows on dual boot now. 

When I did lspci for you, I hadn't got around to reinstalling your drivers.

I'll give that a go when I can get Ethernet on it when I'm home, thanks for the help so far.

**Comment by plane000** [comment] 2018-11-27 21:17
Hey Tomás, 

I don't have any PCI power management thing installed that may be messing with your driver.

Thanks,
Ben

**Comment by tomaspinho** [comment] 2018-11-28 11:05
Ok, just double-checking to make sure we have the basics right:

- Have you disabled SecureBoot in your Thinkpad's BIOS?
- Have your performed these commands?

```
sudo apt-get install --reinstall git dkms build-essential linux-headers-$(uname -r)
git clone https://github.com/tomaspinho/rtl8821ce
cd rtl8821ce
chmod +x dkms-install.sh
chmod +x dkms-remove.sh
sudo ./dkms-install.sh
```

- Have you rebooted since?

**Comment by plane000** [comment] 2018-11-28 20:54
Yeah, i have all of that done, and i just redid it for good measure. Issue persists

**Comment by plane000** [comment] 2018-12-01 10:57
@tomaspinho Would it have anything to do with the working Bluetooth driver that came with this kernel? As I know that the rtl8821 is a WiFi + Bluetooth chip

**Comment by tomaspinho** [comment] 2018-12-03 14:55
Can you post the output of `dmesg`, `lspci -k`, `lsusb -v` and `lsmod` with the 8821ce module loaded and the Bluetooth driver you've just mentioned? I didn't have to blacklist anything to get this working.

**Comment by plane000** [comment] 2018-12-03 21:06
`dmesg`
https://pastebin.com/nD2YnQLB
`lspci -k`
https://pastebin.com/ck2yT7Cy
`lsusp -v`
https://pastebin.com/BJPwyphn
`lsmod`
https://pastebin.com/WmHBTtRL

**Comment by tomaspinho** [comment] 2018-12-05 13:44
There are no association attempts in your log files. Did you try associating? I see multiple app armor audit events around the same time.

There's an abnormal amount of power save events on the interface, but it may just be the case that it's sitting idle. Did you end up enabling the GRUB option as in the README? As a last resort kind of thing you could try installing the module with power saving disabled, by editing the Makefile and changing `CONFIG_POWER_SAVING` to `n`.

**Comment by plane000** [comment] 2018-12-05 22:08
Hey, i'm not sure what you mean by associating. 

However i double checked my gtub config and it's correct, i also recompiled with `CONFIG_POWER_SAVING = n` with no results. (i restarted between and after)

**Comment by tomaspinho** [comment] 2018-12-06 10:23
An association attempt is the technical term for an attempt to connect to a Wi-Fi base station. It looks like your network configuration (applet, service or otherwise) is not  attempting it.

**Comment by ihipop** [comment] 2018-12-12 04:12
Same issue Lenovo E580，In Debian alike system，Kernel 4.15.0，`CONFIG_POWER_SAVING = n` and `pci=noaer` did not do the trick.
set `CONFIG_POWER_SAVING = n` will not appear the message `[25461.435560] RTW: nolinked power save leave` but did not do the trick, still can not connect to network if I disconnected from it，must first `rmmod 8821ce`  then enabled it again.

**Comment by tomaspinho** [comment] 2018-12-12 18:04
@ihipop can you test the code present in https://github.com/tomaspinho/rtl8821ce/pull/16 ?
I've integrated an upstream change from Realtek that may address your issue.

**Comment by ihipop** [comment] 2018-12-13 02:14
> @ihipop can you test the code present in #16 ?
> I've integrated an upstream change from Realtek that may address your issue.

I checkout that branch and rebuild the kernel module,So far so good.
Now I can  reconnect to network if I disconnected from it.

I will continue to  use it until off duty of today to test the stability,I will feedback then

**Comment by ihipop** [comment] 2018-12-14 02:02
> > @ihipop can you test the code present in #16 ?
> > I've integrated an upstream change from Realtek that may address your issue.
> 
> I checkout that branch and rebuild the kernel module,So far so good.
> Now I can reconnect to network if I disconnected from it.
> 
> I will continue to use it until off duty of today to test the stability,I will feedback then

@tomaspinho I use it well at daytime，yeaterday，every thing is working well

so，I think that #16 fix the problem,Which is needed to be merge.

-----------
But,
I disabled the device via Network Manager  when I off duty，
Today morning，When I on duty，I re-enable it via Network Manager

Dmesg:

```
[112836.133029] rtl8821ce 0000:05:00.0: swiotlb buffer is full (sz: 5120 bytes)
[112836.133031] rtl8821ce 0000:05:00.0: DMA: Out of SW-IOMMU space for 5120 bytes
[112836.133294] rtl8821ce 0000:05:00.0: swiotlb buffer is full (sz: 5120 bytes)
[112836.133295] rtl8821ce 0000:05:00.0: DMA: Out of SW-IOMMU space for 5120 bytes
[112836.149547] RTW: ERROR [HALMAC]Polling Bcn_Valid_Fail error!!
[112836.149554] RTW: ERROR [HALMAC]PLATFORM_SEND_RSVD_PAGE 0 error!!
[112836.149555] RTW: ERROR [HALMAC]halmac_send_fwpkt_88xx fail!!
```

Maybe a new bug, Could not fixed by `rmmod 8821ce` and re-enable it again, Should I Open a new  Ticket?

**Comment by tomaspinho** [comment] 2018-12-14 11:19
@ihipop thank you very much for the debugging :+1:.

The thing about maintaining this is that at this point this is already a hacked driver. Realtek does not distribute the code for it on their website and all I'm getting is postings of tarballs of different versions of it in community forums.

There already is a version with a lot of changes posted, which I adapted the change from the MR from, but did not include the other changes as they break compilation.

All I can ask is if you can regularly reproduce that new problem that you've encountered so that we can rule that as a new bug. Please open a new issue so we can track that in there. And then I'll see if I can get sometime to integrate the code in the new version I found.

**Comment by ihipop** [comment] 2018-12-14 16:04
@tomaspinho I will open a new issue of this happens again.
and I think , #16 could be merged at firs for now.,With #16 merged, I can connect and disconnect normally.

**Comment by plane000** [comment] 2018-12-14 16:58
Fix at branch integrate-v5.2.5_1 not reproducible, i might have a different issue though.

**Comment by mamoit** [comment] 2019-01-08 16:36
Using the master branch, and ubuntu 18.10, my dmesg gets spammed by `WARN [TXFOVW]`.
Kernel is `4.18.0-13-generic`.
It seems to have happened only on the upgrade from `4.18.0-12-generic`.

**Comment by DanieleVeri** [comment] 2019-01-20 18:42
> Using the master branch, and ubuntu 18.10, my dmesg gets spammed by `WARN [TXFOVW]`.
> Kernel is `4.18.0-13-generic`.
> It seems to have happened only on the upgrade from `4.18.0-12-generic`.

It's the same for me.

**Comment by tomaspinho** [comment] 2019-02-09 17:41
Closing this due to inactivity.

**Closed by tomaspinho** 2019-02-09 17:41 UTC
