### ISSUE TITLE
Kernel 5.12 support

### ISSUE THREAD

**Issue by grsm2020** [tomaspinho/rtl8821ce#217] opened 2021-03-07 17:40 UTC
Hi and great thanks for your work! I cannot build module for kernel 5.12rc1.

**Comment by tomaspinho** [comment] 2021-03-07 17:55
Please refrain from using this module with 5.12-rc1 for two reasons:

- That's a release candidate, this module is supporting stable releases
- Linus Torvalds has explicitly discouraged users from using that specific version because of swapfile corruption that may cause data loss on your system

If you were trying that kernel out because of our discussion in the Maintenership thread, please try that kernel with the official rtw88 driver for the time being. I will look into making this compile for 5.12 stable before it's released.

**Comment by grsm2020** [comment] 2021-03-07 18:02
Thank u for answer!

**Comment by tomaspinho** [comment] 2021-03-07 18:04
Re-opening as the tracking issue for 5.12 support.

**Comment by ScardracS** [comment] 2021-03-07 20:01
Actually on 5.12_rc2 the WiFI driver made by realtek works without problems

**Comment by tomaspinho** [comment] 2021-03-07 20:28
> Actually on 5.12_rc2 the WiFI driver made by realtek works without problems, be sure to build it as module

That's really good to hear. Do you know your RFE type?

**Comment by grsm2020** [comment] 2021-03-07 20:34
> Actually on 5.12_rc2 the WiFI driver made by realtek works without problems, be sure to build it as module

I need to test it some days or weeks. Now I use 5.12rc2, on 5.12rc1 was have issue: one time random disconnect and no ability to connect again.

**Comment by tomaspinho** [comment] 2021-03-07 22:41
Fix for this module on `5.12-rc2` available at https://github.com/tomaspinho/rtl8821ce/pull/218

**Comment by grsm2020** [comment] 2021-03-08 09:09
Build from new branch was failed on 5.12rc2

**Comment by tomaspinho** [comment] 2021-03-08 10:06
> Build from new branch was failed on 5.12rc2

Can you provide your build logs? It builds just fine on Ubuntu with the mainline 5.12-rc2 kernel packages.

**Comment by grsm2020** [comment] 2021-03-08 10:14
sudo ./dkms-install.sh 
About to run dkms install steps...
Error! DKMS tree already contains: rtl8821ce-v5.5.2_34066.20200325
You cannot add the same module/version combo more than once.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.12.0-0.rc2.165.fc35.x86_64...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.12.0-0.rc2.165.fc35.x86_64 (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.12.0-0.rc2.165.fc35.x86_64...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.12.0-0.rc2.165.fc35.x86_64 (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/make.log for more information.
Finished running dkms install steps.

**Comment by grsm2020** [comment] 2021-03-08 10:15
And simple make have this error.

make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.12.0-0.rc2.165.fc35.x86_64/build M=/home/grsm/rtl8821ce  modules
make[1]: вход в каталог «/usr/src/kernels/5.12.0-0.rc2.165.fc35.x86_64»
  CC [M]  /home/grsm/rtl8821ce/core/rtw_cmd.o
cc1: ошибка: incompatible gcc/plugin versions
cc1: ошибка: failed to initialize plugin ./scripts/gcc-plugins/structleak_plugin.so
make[2]: *** [scripts/Makefile.build:271: /home/grsm/rtl8821ce/core/rtw_cmd.o] Ошибка 1
make[1]: *** [Makefile:1860: /home/grsm/rtl8821ce] Ошибка 2
make[1]: выход из каталога «/usr/src/kernels/5.12.0-0.rc2.165.fc35.x86_64»
make: *** [Makefile:2244: modules] Ошибка 2

**Comment by ScardracS** [comment] 2021-03-08 10:28
Run ./dkms-remove.sh and then install

**Comment by grsm2020** [comment] 2021-03-08 10:37
> Run ./dkms-remove.sh and then install.

Same error anyway.

**Comment by ScardracS** [comment] 2021-03-08 10:41
What log report?

**Comment by grsm2020** [comment] 2021-03-08 10:45
make errors

cc1: ошибка: incompatible gcc/plugin versions
cc1: ошибка: failed to initialize plugin ./scripts/gcc-plugins/structleak_plugin.so
---
script error:

.
Error! DKMS tree already contains: rtl8821ce-v5.5.2_34066.20200325
You cannot add the same module/version combo more than once.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.12.0-0.rc2.165.fc35.x86_64...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.12.0-0.rc2.165.fc35.x86_64 (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/make.log for more information.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 KVER=5.12.0-0.rc2.165.fc35.x86_64...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.12.0-0.rc2.165.fc35.x86_64 (x86_64)
Consult /var/lib/dkms/rtl8821ce/v5.5.2_34066.20200325/build/make.log for more information.
Finished running dkms install steps.
---
I testing built-in driver for now from fedora's rpm build.

**Comment by ScardracS** [comment] 2021-03-08 10:49
You have my same error. Set shell language as english and rebuild. It's a regression with language

**Comment by tomaspinho** [comment] 2021-03-08 10:49
You have a broken GCC installation. Make sure your installed GCC version matches the one used to build your kernel.

**Comment by ScardracS** [comment] 2021-03-08 10:50
> You have a broken GCC installation. Make sure your installed GCC version matches the one used to build your kernel.

No, the problem is with language. I had that error on gentoo too. You have to run LANG="en_US" and then make

**Comment by tomaspinho** [comment] 2021-03-08 12:43
@ScardracS were you able to build this module on 5.12?

**Comment by grsm2020** [comment] 2021-03-08 12:57
> > You have a broken GCC installation. Make sure your installed GCC version matches the one used to build your kernel.
> 
> No, the problem is with language. I had that error on gentoo too. You have to run LANG="en_US" and then make. The kernel checks for gcc and ld and if they doesn't match with "GCC GNU" and "ld GNU" it fails to build. Also check this: https://bugzilla.kernel.org/show_bug.cgi?id=212105
Was tried to change locale with export LANG="en_US" in console window but it don't help.

**Comment by ScardracS** [comment] 2021-03-08 13:07
> @ScardracS were you able to build this module on 5.12?

On gentoo

**Comment by tomaspinho** [comment] 2021-03-08 15:45
> > @ScardracS were you able to build this module on 5.12?
> 
> On gentoo.
> 
> EDIT:
> Did you mean this made by you or the one made by realtek?

I was asking if you had tried building rtl8821ce (this repository) for the 5.12 kernel.

**Comment by ScardracS** [comment] 2021-03-08 16:02
> > > @ScardracS were you able to build this module on 5.12?
> > 
> > On gentoo.
> > 
> > EDIT:
> > Did you mean this made by you or the one made by realtek?
> 
> I was asking if you had tried building rtl8821ce (this repository) for the 5.12 kernel.

Oh, ok. No, I haven't tried this one

**Comment by smekkley** [comment] 2021-03-19 18:28
I confirmed that the official driver from realtek still doesn't work yet on 5.12rc3, Unstable and AP mode broken and all.  
Yet this patch works flawlessly. Thank you. It'd be nice if it was merged to master.

**Comment by tomaspinho** [comment] 2021-03-21 01:31
Thanks for the report! Merged the PR. Closing this one.

**Closed by tomaspinho** 2021-03-21 01:31 UTC
