### ISSUE TITLE
Kubuntu 18.04.2 ERROR (dkms apport): binary package for rtl8821ce:v5.5.2_34066.20190614

### ISSUE THREAD

**Issue by oeriquenes** [tomaspinho/rtl8821ce#57] opened 2019-08-07 18:27 UTC
Hi, i'm trying to install this driver but ...

Kubuntu 18.04.2 
ERROR (dkms apport): binary package for rtl8821ce:v5.5.2_34066.20190614 not found
bad return status for module build on kernel 4.18.0-15-generic
Thx for any help.

**Comment by tomaspinho** [comment] 2019-08-12 10:23
Duplicate of https://github.com/tomaspinho/rtl8821ce/issues/60

**Closed** 2019-08-12 10:22 UTC

**Comment by oeriquenes** [comment] 2019-08-12 16:06
Thx a lot, works fine now!!!
