### ISSUE TITLE
doesn't build against 4.20-rc1

### ISSUE THREAD

**Issue by towo2099** [tomaspinho/rtl8821ce#13] opened 2018-11-13 22:11 UTC
Today i tested linux-4.20-rc1 but sadly the driver doesn't build against that kernel.
Here is the make.log: http://pb.5id.eu/ynz4

**Comment by tomaspinho** [comment] 2018-11-14 21:46
Been digging around and it seems you're missing the file `arch/x86/kernel/macros.s` in your linux headers tree. Just tried building with 4.20.0-rc1 on Ubuntu and found a different compilation problem, which I've fixed.

**Comment by towo2099** [comment] 2018-11-15 05:37
1st that is the drm-next kernel tree, it is 4.20.0-rc1 with the most recent amd-graphics stack from the maintainer (https://cgit.freedesktop.org/~agd5f/linux/?h=drm-next-4.21-wip)
2nd arch/x86/kernel/macros.s does not exist in 4.18.x headers and 4.19.x headers either, but the driver is compiling fine.

**Comment by tomaspinho** [comment] 2018-11-15 10:12
What distribution are you running this kernel under and how did you install the kernel package? I'm trying to create a reproducible environment to debug the build.

**Comment by towo2099** [comment] 2018-11-15 10:47
Disstro is a derivat, based on debian unstable, siduction.
That kernel was build from git checkout https://cgit.freedesktop.org/~agd5f/linux/?h=drm-next-4.21-wip with make bindeb-pkg with the config from the 4.19.2 kernel of siduction.

**Comment by tomaspinho** [comment] 2018-11-17 13:00
That's what I was just researching.

The debs from the linux mainline ppa http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.20-rc1/ install `macros.s`, but anything built from source using the debian config files don't, I tested both the drm-next kernel you were using and a regular linux mainline checkout.

Since the problem is solved, I'm closing this. Thanks for the report!

**Closed by tomaspinho** 2018-11-17 13:00 UTC
